config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "plans#index"
  resources :plans do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :plan

  validates :content, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  # テーブルとのアソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy

  # active_storageとのアソシエーション
  has_one_attached :image

  # 空では保存できない
  with_options presence: true do
    validates :title
    validates :detail
    validates :goal
    validates :start_time
  end

  def self.today_schedule
    today = Date.today
    schedules = Plan.where(start_time: today.beginning_of_day..today.end_of_day)
    schedules.present? ? schedules.first: nil
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plans
  has_many :comments, dependent: :destroy

  with_options presence: true do
    # 半角英数字（空文字NG）以外の場合には、メッセージを出す
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
    validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'

    validates :name
    validates :profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to plan_path(@comment.plan)
    else
      @plan = @comment.plan
      @comments = @plan.comments
      render "plans/show"
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, plan_id: params[:plan_id])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :check_author, only: [:edit, :update, :destroy]

  def index
    @plans = Plan.includes(:user)
    @today_schedule = Plan.today_schedule
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to root_path
    else
      @plans = Plan.includes(:user)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new
    @comments = @plan.comments.includes(:user)
  end

  def edit
  end

  def update
    if @plan.update(plan_params)
      redirect_to plan_path(@plan)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @plan.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:image, :title, :detail, :goal, :start_time).merge(user_id: current_user.id)
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def check_author
    unless current_user == @plan.user
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schema40010</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header" style="background: url(<%= asset_path('banner_02-1230.jpg') %>) center / cover;">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示する %>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "New Post", new_plan_path, class: :nav__btn %>
            </div>
          <% else %>
          <%# // ログインしているときは上記を表示する %>
          <%# ログインしていないときは以下を表示する %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
          <%# // ログインしていないときは上記を表示する %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © SCHEDULE MANAGEMENT All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with model: plan, local: true do |f|%>
  <%= render 'shared/error_messages', model: f.object %>
  
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"plan_title" %>
  </div>

  <div class="field">
    <%= f.label :detail, "詳細" %><br />
    <%= f.text_area :detail, class: :form__text, id:"plan_detail" %>
  </div>

  <div class="field">
    <%= f.label :goal, "目標" %><br />
    <%= f.text_field :goal, id:"plan_goal" %>
  </div>

  <div class="field">
    <%= f.label :start_time, "日付" %><br />
    <%= f.date_select :start_time, id:"plan_start_time" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div class="card">
  <div class="card__body">
    <%= link_to plan.title, plan_path(plan), class: :card__title%>
    <p class="card__summary">
      <%= plan.start_time %>
    </p>
    <%= link_to "by #{plan.user.name}", user_path(plan.user), class: :card__user %>
  </div>
</div>

app/views/plans/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">スケジュール編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { plan: @plan } %>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to "こんにちは、#{current_user.name}さん", user_path(current_user), class: :greeting__link %>
      </div>
    <%# // ログインしているときは上記を表示する %>
    <% end %>
    <% if @today_schedule.present? %>
      <%= link_to "本日は、#{@today_schedule.title}という予定があります", plan_path(@today_schedule.id), class: :greeting__link2 %>
    <% else %>
      <p>本日の予定はありません</p>
    <% end %>
    <div class="card__wrapper">
    </div>
    <br>
    <div class="col-md-8">
      <%= month_calendar events: @plans do |date, plans| %>
        <%= date.day %>

        <% plans.each do |plan| %>
          <div>
            <%= link_to plan.title, plan %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/plans/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規スケジュール投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { plan: @plan } %>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<main class="main">
  <div class="inner">
    <div class="plan__wrapper">
      <p class="plan__hedding">
        <%= @plan.title %>
      </p>
      <%= link_to "by #{@plan.user.name}", user_path(@plan.user), class: :plan__user %>
      <%# 投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @plan.user.id %>
        <div class="plan__manage">
          <%= link_to "編集する", edit_plan_path(@plan), class: :plan__btn %>
          <%= link_to "削除する", plan_path(@plan), data: { turbo_method: :delete }, class: :plan__btn %>
        </div>
      <% end %>
      <%# // 投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="plan__body">
        <div class="plan__detail">
          <p class="detail__title">詳細</p>
          <p class="detail__message">
            <%= @plan.detail %>
          </p>
        </div>
        <div class="plan__detail">
          <p class="detail__title">目標</p>
          <p class="detail__message">
            <%= @plan.goal %>
          </p>
        </div>
        <div class="plan__detail">
          <p class="detail__title">日付</p>
          <p class="detail__message">
            <%= @plan.start_time %>
          </p>
        </div>
      </div>
      <div class="plan__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with model: [@plan, @comment], local: true do |f| %>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %> 
            </div>
          <% end %>
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%= link_to "(#{comment.user.name})", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの予定"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: 'plans/plan', collection: @user.plans %>
      </div>
    </div>
  </div>
</div>